kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-service-depl
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
      version: v01
  template:
    metadata:
      labels:
        app: metrics
        version: v01
    spec:
      containers:
        - name: metrics
          image: cembo/store_metrics:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "metrics-mssql-clusterip-srv"
            - name: DB_NAME
              value: "Store_Metrics"
            - name: DB_USER
              value: "StoreUser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: STOREUSER_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: metrics-clusterip-srv
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: metrics
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: metrics-nodeport-srv
  namespace: store
spec:
  type: NodePort
  selector:
    app: metrics
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008