kind: Deployment
apiVersion: apps/v1
metadata:
  name: ordering-service-depl
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering
      version: v01
  template:
    metadata:
      labels:
        app: ordering
        version: v01
    spec:
      containers:
        - name: ordering
          image: cembo/store_ordering:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "ordering-mssql-clusterip-srv"
            - name: DB_NAME
              value: "Store_Ordering"
            - name: DB_USER
              value: "StoreUser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: STOREUSER_PASSWORD
---

apiVersion: v1
kind: Service
metadata:
  name: ordering-clusterip-srv
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: ordering
  ports:
    - name: ordering
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: ordering-nodeport-srv
  namespace: store
spec:
  type: NodePort
  selector:
    app: ordering
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003