apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-amqp-mssql-depl
  namespace: store
  labels:
    app: inventory-amqp-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-amqp-mssql
  template:
    metadata:
      labels:
        app: inventory-amqp-mssql
    spec:
      containers:
        - name: inventory-amqp-mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: inventory-amqp-mssqldb
      volumes:
      - name: inventory-amqp-mssqldb
        persistentVolumeClaim:
          claimName: inventory-amqp-mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-amqp-consumer-mssql-clusterip-srv
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: inventory-amqp-mssql
  ports:
  - name: inventory-amqp-mssql
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-amqp-consumer-mssql-loadbalancer
  namespace: store
spec:
  type: LoadBalancer
  selector:
    app: inventory-amqp-mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433