kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-amqp-consumer-service-depl
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-amqp-consumer
      version: v01
  template:
    metadata:
      labels:
        app: inventory-amqp-consumer
        version: v01
    spec:
      containers:
        - name: inventory-amqp-consumer
          image: cembo/store_inventory_amqp_consumer:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "inventory-amqp-consumer-mssql-clusterip-srv"
            - name: DB_NAME
              value: "Store_Inventory_AMQP"
            - name: DB_USER
              value: "StoreUser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: STOREUSER_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-amqp-consumer-clusterip-srv
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: inventory-amqp-consumer
  ports:
    - name: inventory-amqp-consumer
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: inventory-amqp-consumer-nodeport-srv
  namespace: store
spec:
  type: NodePort
  selector:
    app: inventory-amqp-consumer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30092