kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-service-depl
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v01
  template:
    metadata:
      labels:
        app: payment
        version: v01
    spec:
      containers:
        - name: payment
          image: cembo/store_payment:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: payment-clusterip-srv
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: payment-nodeport-srv
  namespace: store
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004