kind: Deployment
apiVersion: apps/v1
metadata:
  name: management-service-depl
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
      version: v01
  template:
    metadata:
      labels:
        app: management
        version: v01
    spec:
      containers:
        - name: management
          image: cembo/store_management:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: management-clusterip-srv
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: management
  ports:
    - name: management
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: management-nodeport-srv
  namespace: store
spec:
  type: NodePort
  selector:
    app: management
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007